<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title><?php echo $this->title; ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        
        <?php $bsPath = $this->basePath.'/public/initializr' ?>

        <link rel="stylesheet" href="<?php echo $bsPath; ?>/css/bootstrap.min.css">
        <style>
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
        </style>
        <link rel="stylesheet" href="<?php echo $bsPath; ?>/css/bootstrap-responsive.min.css">
        <link rel="stylesheet" href="<?php echo $bsPath; ?>/css/main.css">

        <script src="<?php echo $bsPath; ?>/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <!-- This code is taken from http://twitter.github.com/bootstrap/examples/hero.html -->

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->basePath ? $this->basePath : '/'?>">Programming test</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <?php foreach ($this->menu as $controller => $item): ?>
                            <?php
                                $classes = array();
                                if ($item['active']) {
                                    $classes[] = 'active';
                                }
                                if (count($item['actions'])) {
                                    $classes[] = 'dropdown';
                                }
                                $url = $this->url(array('controller' => $controller), true);
                            ?>
                            <li<?php echo $classes ? ' class="'.implode(' ', $classes).'"' : '';?>>
                                <?php if (count($item['actions'])): ?>
                                <a href="<?php echo $url; ?>" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->e($item['title'])?> <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <?php foreach ($item['actions'] as $action => $title): ?>
                                    <?php if ($title == '--'): ?>
                                    <li class="divider"></li>
                                    <?php else: ?>
                                    <li><a href="<?php echo $this->url(array('controller' => $controller, 'action' => $action), true) ?>"><?php echo $this->e($title) ?></a></li>
                                    <?php endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                                <?php else: ?>
                                <a href="<?php echo $url; ?>"><?php echo $this->e($item['title'])?></a>
                                <?php endif; ?>
                               </li>
                            <?php endforeach; ?>
                        </ul>
                        <form class="navbar-form pull-right">
                            <input class="span2" type="text" placeholder="Email">
                            <input class="span2" type="password" placeholder="Password">
                            <button type="submit" class="btn">Sign in</button>
                        </form>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">
        
            <?php foreach (\Frmwrk\FlashMessages::getAll() as $message): ?>
            <div class="alert alert-<?php echo $message['class'] ?>">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?php echo $this->translate($message['message']) ?>
            </div>
            <?php endforeach; ?>
        
            <?php echo $this->content; ?>

            <hr>

            <footer>
                <p>&copy; Company 2012</p>
            </footer>

        </div> <!-- /container -->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="<?php echo $bsPath; ?>/js/vendor/jquery-1.9.1.min.js"><\/script>')</script>

        <script src="<?php echo $bsPath; ?>/js/vendor/bootstrap.min.js"></script>

        <script src="<?php echo $bsPath; ?>/js/main.js"></script>
    </body>
</html>